server {
    listen 11000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/service-springboot/ {
        proxy_pass http://service-springboot:11001/;
    }

    location /api/service-quarkus/ {
        proxy_pass http://service-quarkus:11002/;
    }

    location /api/service-go/ {
        proxy_pass http://service-go:11003/;
    }

    location /api/service-node/ {
        proxy_pass http://service-node:11004/;
    }
}
