quarkus.http.port=11002

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=serialplab
quarkus.datasource.password=serialplab
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:11010/serialplab?currentSchema=quarkus
quarkus.hibernate-orm.database.default-schema=quarkus
quarkus.hibernate-orm.database.generation=update

# NATS
nats.url=nats://localhost:11024